### ISSUE TITLE
Colors for terminals

### ISSUE THREAD

**Issue by Rukenshia** [dasupradyumna/midnight.nvim#1]
Hi!

Love the theme and just started using it on my Neovim setup. When I switch themes, I love to match them with my terminal, so would love to have the color palette to use it in Kitty.

Maybe an automated setup using GitHub Actions like tokyonight uses would work well?

https://github.com/folke/tokyonight.nvim/tree/main/lua/tokyonight/extra / https://github.com/folke/tokyonight.nvim/blob/main/.github/workflows/ci.yml#L7

**Comment by dasupradyumna** [comment]
I was planning to add color palettes for various terminal emulators in the future; It will happen soon. :)
I have never thought of automating the process though. Thanks for the references, I'll check them and figure it out!

Cheers ~

**Comment by tom-on-the-internet** [comment]
Plus one. Love this theme.

**Comment by Rukenshia** [comment]
> Please check if this is satisfying. :)
> 
> And since Kitty isn't my primary terminal emulator, please forgive any setting I might have missed out on. You are welcome to submit a PR for adding any such missing reasonable (non-user-personal) setting.
> 
> Cheers ~

Looks great ❤️

**Comment by tom-on-the-internet** [comment]
Amazing. Thank you!
