### ISSUE TITLE
bug: Inlay Hints aren't well supported

### ISSUE THREAD

**Issue by j-barnak** [dasupradyumna/midnight.nvim#11]
### Did you check documentation and existing issues?

- [X] I have read all the midnight.nvim documentation
- [X] I have searched through all existing issues of midnight.nvim
- [X] My issue is non-trivial and does not belong in the Discussions section

### Neovim version (nvim -v)

NVIM v0.10.1-dev-9+g671073e71

### Operating system / version (for eg., uname -sro)

Linux 6.1.0-1036-oem GNU/Linux

### Describe the bug

Inlay hints aren't well supported. They match the background making it impossible to seem

Could fix with just

```lua
vim.api.nvim_set_hl(0, "LspInlayHint", { fg = "#9DA9A0" })
```

### Steps To Reproduce

Enable inlay hints

### Expected Behavior

Inlay hints are a different color than the background

### Repro

```Lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  }
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
require("lazy").setup({
  {
    "dasupradyumna/midnight.nvim",
    lazy = false,
    priority = 1000,
    config = function()
      require('midnight').setup {
        --- add code here
      }
    end,
  }
}, { root = root .. "/plugins" })

vim.cmd.colorscheme "midnight"
```

**Comment by dasupradyumna** [comment]
Hey, I'll make this change soon. Just a bit occupied rn.

**Comment by orzen** [comment]
Check https://github.com/dasupradyumna/midnight.nvim/pull/13

**Comment by pithecantrope** [comment]
This is the best color scheme honestly

**Comment by dasupradyumna** [comment]
Sorry for the extremely late response everyone. I have been busy with my day-job.
Closing this issue because the related MR has been merged.

Thanks @orzen for your efforts! :)
