### ISSUE TITLE
Support documentSymbol Highlight

### ISSUE THREAD

**Issue by SDGLBL** [dasupradyumna/midnight.nvim#3]
As title

**Comment by SDGLBL** [comment]
> I'm afraid I don't understand what you mean; could you elaborate?
> If possible, provide existing examples.

color schema (catppuccin) with symbol highlight
<img width="747" alt="image" src="https://github.com/dasupradyumna/midnight.nvim/assets/41188874/6a7ae610-150c-46cc-8c8e-254e16c6f901">
color schema (midnight) without symbol highlight
<img width="742" alt="image" src="https://github.com/dasupradyumna/midnight.nvim/assets/41188874/91dd5db4-4caf-437a-bd56-71ebfa34fc50">

**Comment by dasupradyumna** [comment]
If it's just a search highlight, **midnight.nvim** already does this.
![issue#3](https://github.com/dasupradyumna/midnight.nvim/assets/45595032/0c2e8937-e143-4353-84b4-316f80e391f0)

But I'm guessing that you have a plugin that highlights document symbols using LSP. Can you check and let me know? I probably did not add support for that plugin yet. 

Could you execute `:Inspect` when the cursor is on a highlighted symbol (with **catppuccin** colorscheme enabled) and post the output here?

**Comment by SDGLBL** [comment]
> 

I use "vim-illuminate"

```
{
        "RRethy/vim-illuminate",
        event = "VeryLazy",
        config = function()
          require("utils.lsp").on_attach(function(client, _)
            require("illuminate").on_attach(client)
          end, { group = "_illuminate_attach", desc = "attach illuminate" })
        end,
 },
```

Inspect output when use catppuccin

<img width="728" alt="image" src="https://github.com/dasupradyumna/midnight.nvim/assets/41188874/ff680ab7-5974-4bc4-b3fe-2ac1f5253e2b">

**Comment by dasupradyumna** [comment]
Let me know if this adds the highlights you wanted. :)

Cheers ~
