### ISSUE TITLE
feature: underline words with incorrect spellings

### ISSUE THREAD

**Issue by vnea** [dasupradyumna/midnight.nvim#7]
### Did you check the documentation and existing issues?

- [X] I have read all the midnight.nvim documentation
- [X] I have searched through all existing issues of midnight.nvim

### Is your feature request related to a problem? Please describe.

I use:
* `Neovim v0.9.4`.
* `dasupradyumna/midnight.nvim v.0.1`

When I enable spell check (set spell), the words with incorrect spellings are not underlined:
![image](https://github.com/dasupradyumna/midnight.nvim/assets/10775422/8f090cfc-fa96-4a21-8be8-4d39b4f8c138)

Whereas with the `default` theme, it works:
![image](https://github.com/dasupradyumna/midnight.nvim/assets/10775422/7481208d-052d-4362-97bb-1edeb095341d)

### Describe the solution you'd like

I want the words with incorrect spellings to be underlined like in the `default` theme.

### Describe alternatives you've considered

Using another theme which supports this feature...

**Comment by vnea** [comment]
When I do that, I have this error:

![image](https://github.com/dasupradyumna/midnight.nvim/assets/10775422/6a00d127-a505-40ce-8d0b-aa36d08bddf4)

But I tried to run `:Inspect!` instead and I got this:

![image](https://github.com/dasupradyumna/midnight.nvim/assets/10775422/256e841a-76be-4005-88c5-d6867eb738ea)

Is it good?

**Comment by vnea** [comment]
Hello.

Any news?

**Comment by dasupradyumna** [comment]
Hey, sorry for the late response, I have been busy with interviews. I think they are mostly related to the **Spellxxx** highlight groups. I'll push the fix soon.
