### ISSUE TITLE
feature: support new treesitter capture names

### ISSUE THREAD

**Issue by seankhliao** [dasupradyumna/midnight.nvim#8]
### Did you check the documentation and existing issues?

- [X] I have read all the midnight.nvim documentation
- [X] I have searched through all existing issues of midnight.nvim

### Is your feature request related to a problem? Please describe.

nvim-treesitter recently changed capture names:
* breaking change announcement: https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1900679583
* documented highlights https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights
* change commit https://github.com/nvim-treesitter/nvim-treesitter/commit/1ae9b0e4558fe7868f8cda2db65239cfb14836d0

which i noticed because my markdown files were no longer highlighted (probably because of `@text.* -> @markup.*`)

### Describe the solution you'd like

Support the new capture names

### Describe alternatives you've considered

temporary: pin nvim-treesitter to v0.9.2

long term: find a different color scheme

**Comment by dasupradyumna** [comment]
Hello, I will update the colorscheme with these changes soon.

**Comment by dasupradyumna** [comment]
Reopen if you think I missed anything. :)
